config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :articles
  delete "articles/:id" => 'articles#destroy', as: "delete_article"

  patch 'articles/:id' => 'articles#update', as: "update"

  get 'dashboard/index'
  root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = current_user.articles.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = current_user.articles.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = current_user.articles.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to dashboard_index_path({new:"notice"}) }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to edit_article_path(params[:id]), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    redirect_to dashboard_index_path({del:"notice"})
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = current_user.articles.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.permit(:title, :description , :body)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index

    if params[:query] == nil || params[:query] == ""
      query_articles = current_user.articles
    else
      query = params[:query]
      query_articles = current_user.articles.where(title:query)
    end

    @q = query_articles.ransack(params[:q])
    @Articles = @q.result(distinct: true)

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    "/"
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= article.description %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_field :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="p-5">
    <h1 class="text-center text-4xl font-fredoka">Editing Article</h1>
    <p class="text-center font-bold" style="color: green"><%= flash.notice %></p>

    <%= form_with url: update_path ,method: :patch  do |form| %>
    <div class="ml-7">
        <%= form.label "Title:",class:"font-bold" %>
        <%= form.text_field :title , value: @article.title, required:true,size:"20x1",class:"border-none"%>
    </div>

    <div class="ml-7">
        <%= form.label "Description:" ,class:"font-bold"%>
        <%= form.text_field :description , value: @article.description, required:true,size:"80x1",class:"border-none" %>
    </div>

    <div class="flex justify-center mt-3">
        <%= form.text_area :body ,value: @article.body, size: "130x20"%>
    </div>

    </br>
    <div class="flex justify-center">
        <%= form.submit "Update", class:"bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded" %>
    </div>

    <% end %>

    </br>
    <div class="flex justify-center">
        <%= button_to "back to Dashboard",dashboard_index_path , method: :get, class:"bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded"%> 
    </div>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", article %>
    </p>
  <% end %>
</div>

<%= link_to "New article", new_article_path %>

app/views/articles/new.html.erb
<div class="p-5">
    <h1 class="text-center text-4xl font-fredoka">New article</h1>

    <%= form_with url: "/articles" do |form| %>
    <div class="ml-7">
        <%= form.label "Title:",class:"font-bold" %>
        <%= form.text_field :title , required:true,size:"20x1",class:"border-none"%>
    </div>

    <div class="ml-7">
        <%= form.label "Description:" ,class:"font-bold"%>
        <%= form.text_field :description , required:true,size:"80x1",class:"border-none" %>
    </div>

    <div class="flex justify-center mt-3">
        <%= form.text_area :body , size: "130x20"%>
    </div>

    </br>
    <div class="flex justify-center">
        <%= form.submit "Submit", class:"bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded" %>
    </div>

    <% end %>

    </br>
    <div class="flex justify-center">
        <%= button_to "back to Dashboard",dashboard_index_path , method: :get, class:"bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded"%> 
    </div>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/dashboard/index.html.erb
<div class="p-8">
  <h1 class="font-fredoka text-xl">Welcome to your Blog! ,</h1>
  <h1 class="font-gochi text-xl"><%= current_user.email%></h1>
  <h4>Date: <%= Date.today.strftime("%B %d, %Y") %></h4>
  <%= button_to "Log Out",destroy_user_session_path, method: :delete, class:"bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded"%>      
  </br>
  <div class="flex flex-col items-center bg-amber-200 w-max mx-auto p-10 rounded-2xl min-h-[500px]">
    <%= button_to "Create New Article" ,new_article_path , method: :get, class:"bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded"%>  
    <div class="mt-5">
      <%= form_with url: "/dashboard/index", method: :get do |form| %>
        <%= form.text_field :query ,size: "10x1", placeholder:"search title"%>
        <%= form.submit "Search", class:"bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded"%>
      <% end %>
    </div>

    <div class="mt-4">
      <% if params[:del] == "notice" %>
        <p class = "font-bold text-red-600">Article was successfully deleted.</p>
      <% elsif params[:new] == "notice"%>
        <p class = "font-bold text-green-600">Article was successfully created.</p>
      <% end %>
    </div>

    <div class="flex flex-col">
      <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="inline-block min-w-full sm:px-6 lg:px-8">
          <div class="overflow-hidden">
            <table class="table-auto mt-3">
              <thead class="border-b">
                <tr>
                  <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">#</th>
                  <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left hover:underline"><%= sort_link(@q, :title, 'Article Title', default_order: :asc) %></th>
                  <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Description</th>
                  <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left hover:underline"><%= sort_link(@q, :created_at, 'Date Created', default_order: :asc) %></th>
                  <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left hover:underline"><%= sort_link(@q, :updated_at, 'Date Modified', default_order: :asc) %></th>
                  <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Delete Article</th>
                </tr>
              </thead>
              <tbody>
                <% @Articles.each_with_index do |article,index| %>
                <tr class="border-b"> 
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"><%=index+1%></td>
                  <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap hover:scale-125 hover:font-bold" ><%= link_to article.title, edit_article_path(article.id)%></td>
                  <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap"><%= article.description %></td>
                  <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap"><%= article.created_at.strftime("%I:%M%p/%b %d") %></td>
                  <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap"><%= article.updated_at.strftime("%I:%M%p/%b %d") %></td>
                  <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap"><%= button_to "Delete",delete_article_path(article.id), method: :delete, class:"bg-red-500 hover:bg-red-700 text-white font-bold py-1.5 px-3 rounded"%>      </td>
                </tr>
                <% end %>
              </tbody>
            </table> 
          </div>
        </div>
      </div>
    </div>            
  </div>
  </br>
  </br>
</div>

app/views/home/index.html.erb
<div class="bg-cover bg-no-repeat h-screen w-screen" style="background-image: url('https://res.cloudinary.com/dazff5yba/image/upload/v1668143940/Blog_bg_owwakz.jpg')">
  <div class="w-1/3 mx-auto text-center absolute right-20 bottom-10 top-10 bg-amber-400 h-9/10 rounded-2xl pt-10">
    <h2 class="font-rock text-7xl">Welcome to JP Blog App</h2>  
    <div class="flex justify-center gap-x-5 mt-20 ">
        <%= button_to "Log in", dashboard_index_path, method: :get, class:"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"%>
        <%= button_to "Register", new_user_registration_path, method: :get, class:"bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded"%>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fredoka+One&family=Gochi+Hand&family=Rock+Salt&display=swap" rel="stylesheet"> 

  </head>

  <body>
    <%= yield %>

  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>